# Generated by Django 3.2.9 on 2022-02-27 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('nId', models.IntegerField(primary_key=True, serialize=False)),
                ('nName', models.CharField(max_length=100)),
                ('nPhone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vNum', models.IntegerField(primary_key=True, serialize=False)),
                ('vName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('vType', models.CharField(max_length=10)),
                ('vId', models.IntegerField(primary_key=True, serialize=False)),
                ('vName', models.CharField(max_length=100)),
                ('vPlace', models.CharField(max_length=100)),
                ('vAge', models.IntegerField()),
                ('vNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pId', models.IntegerField(primary_key=True, serialize=False)),
                ('pName', models.CharField(max_length=100)),
                ('pType', models.CharField(max_length=10)),
                ('pAge', models.IntegerField()),
                ('house', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('pno1', models.IntegerField()),
                ('pno2', models.IntegerField()),
                ('disease', models.CharField(max_length=100)),
                ('dor', models.CharField(max_length=100)),
                ('nId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.nurse')),
            ],
        ),
        migrations.AddField(
            model_name='nurse',
            name='vNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.vehicle'),
        ),
    ]
